version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nammalvar_db
    environment:
      POSTGRES_DB: nammalvar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nammalvar_backend
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:Password@db:5432/nammalvar_db
      - DEBUG=True
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nammalvar_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
