# Generated by Django 6.0.5 on 2026-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cereals', 'Cereals'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Pulses', 'Pulses'), ('Oil Seeds', 'Oil Seeds')], max_length=30),
        ),
    ]
